package postgresql

import (
	"crypto/rsa"
	"errors"
	"testing"

	"github.com/fclairamb/dbbat/internal/config"
)

func TestLoadTLS_Disabled(t *testing.T) {
	t.Parallel()

	tlsConf, err := loadTLS(config.PGConfig{
		TLS: config.TLSConfig{Disable: true},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if tlsConf != nil {
		t.Error("expected nil tls.Config when disabled")
	}
}

func TestLoadTLS_AutoGenerated(t *testing.T) {
	t.Parallel()

	tlsConf, err := loadTLS(config.PGConfig{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if tlsConf == nil {
		t.Fatal("expected non-nil tls.Config")
	}

	if len(tlsConf.Certificates) != 1 {
		t.Fatalf("expected 1 certificate, got %d", len(tlsConf.Certificates))
	}

	if _, ok := tlsConf.Certificates[0].PrivateKey.(*rsa.PrivateKey); !ok {
		t.Error("certificate private key should be *rsa.PrivateKey")
	}
}

func TestLoadTLS_PartialPathsRejected(t *testing.T) {
	t.Parallel()

	cases := []config.TLSConfig{
		{CertFile: "cert.pem"},
		{KeyFile: "key.pem"},
	}

	for _, tc := range cases {
		_, err := loadTLS(config.PGConfig{TLS: tc})
		if !errors.Is(err, ErrTLSConfigInvalid) {
			t.Errorf("expected ErrTLSConfigInvalid for %+v, got %v", tc, err)
		}
	}
}
