branches:
  - main

plugins:
  # Analyze commits to determine version bump
  - "@semantic-release/commit-analyzer"

  # Generate release notes from commits
  - "@semantic-release/release-notes-generator"

  # Update CHANGELOG.md
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md

  # Commit updated CHANGELOG.md and package.json
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

  # Create GitHub release
  - "@semantic-release/github"
