{{- if .Values.service.proxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" (include "dbbat.fullname" .) (default "proxy" .Values.service.proxy.nameSuffix) | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "dbbat.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  {{- with .Values.service.proxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.proxy.type }}
  {{- with .Values.service.proxy.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.service.proxy.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
    {{- if .Values.service.oracle.enabled }}
    - port: {{ .Values.service.oracle.port }}
      targetPort: oracle
      protocol: TCP
      name: oracle
    {{- end }}
    {{- if .Values.service.mysql.enabled }}
    - port: {{ .Values.service.mysql.port }}
      targetPort: mysql
      protocol: TCP
      name: mysql
    {{- end }}
  selector:
    {{- include "dbbat.selectorLabels" . | nindent 4 }}
{{- end }}
