-- Which format connections.query_chain_mac is in.
--
-- The stamp shipped in 0.23.x as a *verbatim copy* of the last statement's
-- MAC. That value is readable straight out of `queries`, so an attacker with
-- write access to this database could delete the tail of a session and copy
-- the new last statement's MAC over the stamp — no key required, and
-- `dbbat audit verify --queries` reported a clean chain. From this migration
-- onward the stamp is HMAC(chain key, domain ‖ connection_id ‖ version ‖
-- query_chain_len ‖ head_mac), which cannot be recomputed without the key.
--
-- The two formats have to coexist: the chain key lives only in the serving
-- process, never in the database, so no migration can re-seal what is already
-- stored. Hence a version rather than a flag day — every row that exists right
-- now is version 0 (legacy, unkeyed) and every session closed from here on is
-- version 1 (keyed). Verification picks the check by version and counts the
-- version 0 rows, so an operator can watch how much of the store is still on
-- the forgeable stamp.
--
-- The version is also covered by the version 1 MAC. Without that, relabelling
-- a sealed row as version 0 would buy the attacker the legacy check for free.
ALTER TABLE connections
    ADD COLUMN query_chain_stamp_version SMALLINT NOT NULL DEFAULT 0;
