-- Records whether the proxy→upstream leg of a session was actually encrypted.
--
-- ssl_mode on the server row states a *policy*, not an outcome. Under the
-- opportunistic modes ("prefer", and the empty default that every unset row
-- carries) dbbat offers TLS and falls back to plaintext when the target refuses
-- — which is exactly what makes those modes usable, and exactly what makes them
-- impossible to audit from configuration alone. Two sessions against the same
-- row, minutes apart, can differ if the target's TLS was reloaded in between.
--
-- Without this column "are we actually encrypted?" is a guess. With it, the
-- fallback is safe to keep: a downgrade is recorded rather than silent, and an
-- operator can find the rows where it happened instead of inferring it.
--
-- NOT NULL DEFAULT false: rows written before this migration were opened by a
-- build with no opportunistic TLS on MySQL or MongoDB, and by a PostgreSQL path
-- that did not report what it negotiated. "false" is the honest reading of a
-- row that never measured it — deliberately not NULL, because a nullable
-- boolean here would invite "unknown" to be treated as "encrypted".
ALTER TABLE connections ADD COLUMN IF NOT EXISTS upstream_tls BOOLEAN NOT NULL DEFAULT false;
