/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the API server and database connection.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get version information
         * @description Returns API version and build information.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login and create web session
         * @description Authenticates with username/password and creates a short-lived web session token.
         *
         *     The token should be stored and used as a Bearer token for subsequent API calls.
         *     Web session tokens expire after 1 hour.
         *
         *     **Important**: Users who haven't changed their initial password will receive a 403 error.
         *     They must first change their password using `PUT /auth/password` before logging in.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout and revoke web session
         * @description Revokes the current web session token.
         *
         *     After logout, the token will no longer be valid for authentication.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user and session info
         * @description Returns information about the currently authenticated user and their session.
         *
         *     Use this endpoint to:
         *     - Validate that a session token is still valid
         *     - Check if password change is required
         *     - Get session expiration time
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change password (pre-login)
         * @description Allows users to change their password before logging in.
         *     Used for initial password change or password reset flows.
         *
         *     Does not require authentication - validates username/current_password.
         *     Subject to rate limiting (same as login).
         *
         *     After changing password, users can login using `POST /auth/login`.
         */
        put: operations["changePasswordPreLogin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Returns a list of users.
         *
         *     - Admins see all users
         *     - Non-admins see only themselves
         */
        get: operations["listUsers"];
        put?: never;
        /**
         * Create a new user
         * @description Creates a new user account. Requires admin role.
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UID */
                uid: components["parameters"]["UserUID"];
            };
            cookie?: never;
        };
        /**
         * Get user by UID
         * @description Retrieves a specific user by their UID.
         */
        get: operations["getUser"];
        /**
         * Update user
         * @description Updates a user account.
         *
         *     - Non-admins can only update their own password
         *     - Non-admins cannot change roles
         *     - API keys cannot change passwords (requires Basic Auth)
         */
        put: operations["updateUser"];
        post?: never;
        /**
         * Delete user
         * @description Deletes a user account. Requires admin role.
         *
         *     Note: Cannot delete your own user account.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{uid}/password": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UID */
                uid: components["parameters"]["UserUID"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Change password (authenticated)
         * @description Changes a user's password. Requires re-authentication via username/password in the request body.
         *
         *     **Important**: This endpoint does NOT use Bearer token authentication.
         *     Users must provide their username and current password for re-authentication.
         *
         *     - Users can only change their own password
         *     - Admin users can change any user's password (with their own admin credentials)
         *     - Subject to rate limiting (same as login)
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List databases
         * @description Returns a list of database configurations.
         *
         *     Response varies by role:
         *     - **Admin**: Full details (host, port, database_name, username, ssl_mode)
         *     - **Viewer**: Limited info (uid, name, description)
         *     - **Connector**: Only databases they have active grants for (limited info)
         */
        get: operations["listDatabases"];
        put?: never;
        /**
         * Create database configuration
         * @description Creates a new database configuration. Requires admin role.
         */
        post: operations["createDatabase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/databases/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Database UID */
                uid: components["parameters"]["DatabaseUID"];
            };
            cookie?: never;
        };
        /**
         * Get database by UID
         * @description Retrieves a specific database configuration.
         *
         *     Response varies by role:
         *     - **Admin**: Full details
         *     - **Viewer**: Limited info
         *     - **Connector**: Only if they have an active grant (limited info)
         */
        get: operations["getDatabase"];
        /**
         * Update database
         * @description Updates a database configuration. Requires admin role.
         */
        put: operations["updateDatabase"];
        post?: never;
        /**
         * Delete database
         * @description Deletes a database configuration. Requires admin role.
         */
        delete: operations["deleteDatabase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List grants
         * @description Returns a list of access grants.
         *
         *     Connectors can only see their own grants.
         */
        get: operations["listGrants"];
        put?: never;
        /**
         * Create access grant
         * @description Creates a new access grant for a user to a database. Requires admin role.
         */
        post: operations["createGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grants/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Grant UID */
                uid: components["parameters"]["GrantUID"];
            };
            cookie?: never;
        };
        /**
         * Get grant by UID
         * @description Retrieves a specific access grant.
         *
         *     Connectors can only see their own grants.
         */
        get: operations["getGrant"];
        put?: never;
        post?: never;
        /**
         * Revoke grant
         * @description Revokes an access grant. Requires admin role.
         */
        delete: operations["revokeGrant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description Returns a list of API keys.
         *
         *     - Non-admins can only see their own keys
         *     - Admins can see all keys (optionally filter by user_id)
         */
        get: operations["listAPIKeys"];
        put?: never;
        /**
         * Create API key
         * @description Creates a new API key for the authenticated user.
         *
         *     **Important**: The full API key is only returned once in this response.
         *     Store it securely as it cannot be retrieved later.
         *
         *     Requires Web Session or Basic Auth (API keys cannot create other API keys).
         */
        post: operations["createAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key ID */
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get API key by ID
         * @description Retrieves a specific API key.
         *
         *     Non-admins can only see their own keys.
         */
        get: operations["getAPIKey"];
        put?: never;
        post?: never;
        /**
         * Revoke API key
         * @description Revokes an API key.
         *
         *     - Non-admins can only revoke their own keys
         *     - Requires Web Session or Basic Auth (API keys cannot revoke API keys)
         */
        delete: operations["revokeAPIKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List connections
         * @description Returns a list of proxy connections.
         *
         *     Connectors can only see their own connections.
         */
        get: operations["listConnections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List queries
         * @description Returns a list of executed queries.
         *
         *     Requires admin or viewer role.
         */
        get: operations["listQueries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{uid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Query UID */
                uid: components["parameters"]["QueryUID"];
            };
            cookie?: never;
        };
        /**
         * Get query details
         * @description Retrieves a specific query without its result rows.
         *
         *     Use `GET /queries/{uid}/rows` to retrieve the result rows.
         *
         *     Requires admin or viewer role.
         */
        get: operations["getQuery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queries/{uid}/rows": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Query UID */
                uid: components["parameters"]["QueryUID"];
            };
            cookie?: never;
        };
        /**
         * List query result rows (paginated)
         * @description Retrieves paginated result rows for a specific query.
         *
         *     Uses cursor-based pagination with two limits per request:
         *     - Maximum 1000 rows per response
         *     - Maximum 1MB of row data per response
         *
         *     The response stops at whichever limit is reached first.
         *
         *     Requires admin or viewer role.
         */
        get: operations["getQueryRows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List audit events
         * @description Returns a list of audit log events.
         *
         *     Requires admin or viewer role.
         */
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description API and build version information */
        VersionInfo: {
            /**
             * @description API version (e.g., "v1")
             * @example v1
             */
            api_version: string;
            /**
             * @description Build version
             * @example 1.2.3
             */
            build_version: string;
            /**
             * @description Git commit hash
             * @example abc1234
             */
            build_commit: string;
            /**
             * Format: date-time
             * @description Build timestamp
             * @example 2026-01-09T12:00:00Z
             */
            build_time: string;
        };
        LoginRequest: {
            /** @description Username */
            username: string;
            /**
             * Format: password
             * @description Password
             */
            password: string;
        };
        LoginResponse: {
            /** @description Web session token (use as Bearer token) */
            token: string;
            /**
             * Format: date-time
             * @description Token expiration time
             */
            expires_at: string;
            user: components["schemas"]["AuthUser"];
        };
        /** @description User info returned in auth responses */
        AuthUser: {
            /**
             * Format: uuid
             * @description User UID
             */
            uid: string;
            /** @description Username */
            username: string;
            /** @description User roles */
            roles: ("admin" | "viewer" | "connector")[];
            /** @description Whether user must change their password */
            password_change_required: boolean;
        };
        MeResponse: {
            /**
             * Format: uuid
             * @description User UID
             */
            uid: string;
            /** @description Username */
            username: string;
            /** @description User roles */
            roles: ("admin" | "viewer" | "connector")[];
            /** @description Whether user must change their password */
            password_change_required: boolean;
            session: components["schemas"]["SessionInfo"];
        };
        /** @description Current session information */
        SessionInfo: {
            /**
             * Format: date-time
             * @description Session expiration time
             */
            expires_at?: string;
            /**
             * Format: date-time
             * @description Session creation time
             */
            created_at?: string;
        };
        /** @description Request for authenticated password change (re-authentication required) */
        ChangePasswordRequest: {
            /** @description Username for re-authentication */
            username: string;
            /**
             * Format: password
             * @description Current password for re-authentication
             */
            current_password: string;
            /**
             * Format: password
             * @description New password (minimum 8 characters)
             */
            new_password: string;
        };
        /** @description Request for pre-login password change (no token required) */
        PreLoginPasswordChangeRequest: {
            /** @description Username */
            username: string;
            /**
             * Format: password
             * @description Current/temporary password
             */
            current_password: string;
            /**
             * Format: password
             * @description New password (minimum 8 characters)
             */
            new_password: string;
        };
        User: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            uid: string;
            /** @description Username */
            username: string;
            /** @description User roles */
            roles: ("admin" | "viewer" | "connector")[];
            /** @description Whether user bypasses rate limiting */
            rate_limit_exempt: boolean;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Format: date-time
             * @description Last update timestamp
             */
            updated_at: string;
        };
        CreateUserRequest: {
            /** @description Username */
            username: string;
            /** @description Password */
            password: string;
            /** @description User roles */
            roles?: ("admin" | "viewer" | "connector")[];
        };
        UpdateUserRequest: {
            /** @description New password */
            password?: string;
            /** @description New roles (admin only) */
            roles?: ("admin" | "viewer" | "connector")[];
        };
        /** @description Full database details (admin only) */
        Database: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            uid: string;
            /** @description Database configuration name */
            name: string;
            /** @description Description */
            description?: string;
            /** @description Target database host */
            host?: string;
            /** @description Target database port */
            port?: number;
            /** @description Target database name */
            database_name?: string;
            /** @description Target database username */
            username?: string;
            /** @description SSL mode (disable, prefer, require, etc.) */
            ssl_mode?: string;
            /**
             * Format: uuid
             * @description User who created this configuration
             */
            created_by?: string | null;
        };
        /** @description Limited database info for non-admin users */
        DatabaseLimited: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            uid: string;
            /** @description Database configuration name */
            name: string;
            /** @description Description */
            description?: string;
        };
        CreateDatabaseRequest: {
            /** @description Unique name for this database configuration */
            name: string;
            /** @description Description */
            description?: string;
            /** @description Target database host */
            host: string;
            /**
             * @description Target database port
             * @default 5432
             */
            port: number;
            /** @description Target database name */
            database_name: string;
            /** @description Target database username */
            username: string;
            /** @description Target database password (encrypted at rest) */
            password: string;
            /**
             * @description SSL mode
             * @default prefer
             */
            ssl_mode: string;
        };
        UpdateDatabaseRequest: {
            /** @description Description */
            description?: string;
            /** @description Target database host */
            host?: string;
            /** @description Target database port */
            port?: number;
            /** @description Target database name */
            database_name?: string;
            /** @description Target database username */
            username?: string;
            /** @description Target database password (encrypted at rest) */
            password?: string;
            /** @description SSL mode */
            ssl_mode?: string;
        };
        AccessGrant: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            uid: string;
            /**
             * Format: uuid
             * @description User UID
             */
            user_id: string;
            /**
             * Format: uuid
             * @description Database UID
             */
            database_id: string;
            /**
             * @description Access level
             * @enum {string}
             */
            access_level: "read" | "write";
            /**
             * Format: uuid
             * @description Admin who granted access
             */
            granted_by: string;
            /**
             * Format: date-time
             * @description When access starts
             */
            starts_at: string;
            /**
             * Format: date-time
             * @description When access expires
             */
            expires_at: string;
            /**
             * Format: date-time
             * @description When access was revoked (null if active)
             */
            revoked_at?: string | null;
            /**
             * Format: uuid
             * @description Admin who revoked access
             */
            revoked_by?: string | null;
            /**
             * Format: int64
             * @description Maximum queries allowed (quota)
             */
            max_query_counts?: number | null;
            /**
             * Format: int64
             * @description Maximum bytes transferred (quota)
             */
            max_bytes_transferred?: number | null;
            /**
             * Format: int64
             * @description Current query count
             */
            query_count?: number;
            /**
             * Format: int64
             * @description Current bytes transferred
             */
            bytes_transferred?: number;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
        };
        CreateGrantRequest: {
            /**
             * Format: uuid
             * @description User UID
             */
            user_id: string;
            /**
             * Format: uuid
             * @description Database UID
             */
            database_id: string;
            /**
             * @description Access level
             * @enum {string}
             */
            access_level: "read" | "write";
            /**
             * Format: date-time
             * @description When access starts
             */
            starts_at: string;
            /**
             * Format: date-time
             * @description When access expires (must be after starts_at)
             */
            expires_at: string;
            /**
             * Format: int64
             * @description Maximum queries allowed (quota)
             */
            max_query_counts?: number;
            /**
             * Format: int64
             * @description Maximum bytes transferred (quota)
             */
            max_bytes_transferred?: number;
        };
        APIKey: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            id: string;
            /**
             * Format: uuid
             * @description User UID
             */
            user_id: string;
            /** @description Key name */
            name: string;
            /** @description Key prefix for identification */
            key_prefix: string;
            /**
             * Format: date-time
             * @description When the key expires
             */
            expires_at?: string | null;
            /**
             * Format: date-time
             * @description When the key was last used
             */
            last_used_at?: string | null;
            /**
             * Format: int64
             * @description Total requests made with this key
             */
            request_count: number;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
            /**
             * Format: date-time
             * @description When the key was revoked
             */
            revoked_at?: string | null;
            /**
             * Format: uuid
             * @description User who revoked the key
             */
            revoked_by?: string | null;
        };
        CreateAPIKeyRequest: {
            /** @description Key name */
            name: string;
            /**
             * Format: date-time
             * @description Optional expiration time
             */
            expires_at?: string;
        };
        CreateAPIKeyResponse: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            id: string;
            /** @description Key name */
            name: string;
            /** @description Full API key (only shown once!) */
            key: string;
            /** @description Key prefix for identification */
            key_prefix: string;
            /**
             * Format: date-time
             * @description When the key expires
             */
            expires_at?: string | null;
            /**
             * Format: date-time
             * @description Creation timestamp
             */
            created_at: string;
        };
        Connection: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            uid: string;
            /**
             * Format: uuid
             * @description User UID
             */
            user_id: string;
            /**
             * Format: uuid
             * @description Database UID
             */
            database_id: string;
            /** @description Client IP address */
            source_ip: string;
            /**
             * Format: date-time
             * @description Connection start time
             */
            connected_at: string;
            /**
             * Format: date-time
             * @description Last activity timestamp
             */
            last_activity_at: string;
            /**
             * Format: date-time
             * @description Connection end time (null if still connected)
             */
            disconnected_at?: string | null;
            /**
             * Format: int64
             * @description Number of queries executed
             */
            queries: number;
            /**
             * Format: int64
             * @description Total bytes transferred
             */
            bytes_transferred: number;
        };
        Query: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            uid: string;
            /**
             * Format: uuid
             * @description Connection UID
             */
            connection_id: string;
            /** @description SQL query text */
            sql_text: string;
            parameters?: components["schemas"]["QueryParameters"];
            /**
             * Format: date-time
             * @description Execution timestamp
             */
            executed_at: string;
            /**
             * Format: double
             * @description Execution duration in milliseconds
             */
            duration_ms?: number | null;
            /**
             * Format: int64
             * @description Number of rows affected
             */
            rows_affected?: number | null;
            /** @description Error message if query failed */
            error?: string | null;
        };
        /** @description Query parameter values (for prepared statements) */
        QueryParameters: {
            /** @description Decoded string representations */
            values?: string[];
            /** @description Base64-encoded raw bytes */
            raw?: string[];
            /** @description Format codes (0=text, 1=binary) */
            format_codes?: number[];
            /** @description PostgreSQL type OIDs */
            type_oids?: number[];
        };
        QueryWithRows: components["schemas"]["Query"] & {
            /** @description Result rows (from SELECT or COPY operations) */
            rows?: components["schemas"]["QueryRow"][];
        };
        QueryRow: {
            /** @description Row index */
            row_number: number;
            /** @description Row data as JSON object */
            row_data: {
                [key: string]: unknown;
            };
            /**
             * Format: int64
             * @description Row size in bytes
             */
            row_size_bytes: number;
        };
        /** @description Paginated query rows response */
        QueryRowsResponse: {
            /** @description Array of row objects */
            rows: components["schemas"]["QueryRow"][];
            /** @description Cursor for the next page (null if no more rows) */
            next_cursor?: string | null;
            /** @description Whether more rows are available */
            has_more: boolean;
            /**
             * Format: int64
             * @description Total number of rows for this query
             */
            total_rows: number;
        };
        AuditEvent: {
            /**
             * Format: uuid
             * @description Unique identifier
             */
            uid: string;
            /** @description Event type (e.g., user.created, grant.revoked) */
            event_type: string;
            /**
             * Format: uuid
             * @description User being acted upon
             */
            user_id?: string | null;
            /**
             * Format: uuid
             * @description User performing the action
             */
            performed_by?: string | null;
            /** @description Event-specific details */
            details?: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description Event timestamp
             */
            created_at: string;
        };
        Error: {
            /** @description Error message */
            error: string;
        };
        RateLimitError: {
            /** @example rate_limit_exceeded */
            error: string;
            /** @example Too many requests. Please retry after 60 seconds. */
            message: string;
            /** @description Seconds until retry is allowed */
            retry_after: number;
        };
        /** @description Returned when user hasn't changed their initial password */
        PasswordChangeRequiredError: {
            /**
             * @example password_change_required
             * @enum {string}
             */
            error: "password_change_required";
            /** @example You must change your password before accessing the API */
            message: string;
        };
        /** @description Returned when too many failed login attempts */
        AuthRateLimitedError: {
            /**
             * @example auth_rate_limited
             * @enum {string}
             */
            error: "auth_rate_limited";
            /** @example Too many failed login attempts. Try again in 30 seconds. */
            message: string;
            /**
             * @description Seconds until retry is allowed
             * @example 30
             */
            retry_after: number;
        };
        MessageResponse: {
            /** @description Success message */
            message: string;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Authentication required or invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many failed authentication attempts */
        AuthRateLimited: {
            headers: {
                /** @description Seconds until retry is allowed */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthRateLimitedError"];
            };
        };
        /** @description Insufficient permissions or password change required */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"] | components["schemas"]["PasswordChangeRequiredError"];
            };
        };
        /** @description User must change their initial password before accessing the API */
        PasswordChangeRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PasswordChangeRequiredError"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rate limit exceeded */
        RateLimited: {
            headers: {
                /** @description Seconds until retry is allowed */
                "Retry-After"?: number;
                /** @description Maximum requests per minute */
                "X-RateLimit-Limit"?: number;
                /** @description Remaining requests in current window */
                "X-RateLimit-Remaining"?: number;
                /** @description Unix timestamp when limit resets */
                "X-RateLimit-Reset"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RateLimitError"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description User UID */
        UserUID: string;
        /** @description Database UID */
        DatabaseUID: string;
        /** @description Grant UID */
        GrantUID: string;
        /** @description Query UID */
        QueryUID: string;
        /** @description Maximum number of results to return */
        Limit: number;
        /** @description Number of results to skip for pagination */
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type VersionInfo = components['schemas']['VersionInfo'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type LoginResponse = components['schemas']['LoginResponse'];
export type AuthUser = components['schemas']['AuthUser'];
export type MeResponse = components['schemas']['MeResponse'];
export type SessionInfo = components['schemas']['SessionInfo'];
export type ChangePasswordRequest = components['schemas']['ChangePasswordRequest'];
export type PreLoginPasswordChangeRequest = components['schemas']['PreLoginPasswordChangeRequest'];
export type User = components['schemas']['User'];
export type CreateUserRequest = components['schemas']['CreateUserRequest'];
export type UpdateUserRequest = components['schemas']['UpdateUserRequest'];
export type Database = components['schemas']['Database'];
export type DatabaseLimited = components['schemas']['DatabaseLimited'];
export type CreateDatabaseRequest = components['schemas']['CreateDatabaseRequest'];
export type UpdateDatabaseRequest = components['schemas']['UpdateDatabaseRequest'];
export type AccessGrant = components['schemas']['AccessGrant'];
export type CreateGrantRequest = components['schemas']['CreateGrantRequest'];
export type ApiKey = components['schemas']['APIKey'];
export type CreateApiKeyRequest = components['schemas']['CreateAPIKeyRequest'];
export type CreateApiKeyResponse = components['schemas']['CreateAPIKeyResponse'];
export type Connection = components['schemas']['Connection'];
export type Query = components['schemas']['Query'];
export type QueryParameters = components['schemas']['QueryParameters'];
export type QueryWithRows = components['schemas']['QueryWithRows'];
export type QueryRow = components['schemas']['QueryRow'];
export type QueryRowsResponse = components['schemas']['QueryRowsResponse'];
export type AuditEvent = components['schemas']['AuditEvent'];
export type Error = components['schemas']['Error'];
export type RateLimitError = components['schemas']['RateLimitError'];
export type PasswordChangeRequiredError = components['schemas']['PasswordChangeRequiredError'];
export type AuthRateLimitedError = components['schemas']['AuthRateLimitedError'];
export type MessageResponse = components['schemas']['MessageResponse'];
export type ResponseBadRequest = components['responses']['BadRequest'];
export type ResponseUnauthorized = components['responses']['Unauthorized'];
export type ResponseAuthRateLimited = components['responses']['AuthRateLimited'];
export type ResponseForbidden = components['responses']['Forbidden'];
export type ResponsePasswordChangeRequired = components['responses']['PasswordChangeRequired'];
export type ResponseNotFound = components['responses']['NotFound'];
export type ResponseRateLimited = components['responses']['RateLimited'];
export type ResponseInternalError = components['responses']['InternalError'];
export type ParameterUserUid = components['parameters']['UserUID'];
export type ParameterDatabaseUid = components['parameters']['DatabaseUID'];
export type ParameterGrantUid = components['parameters']['GrantUID'];
export type ParameterQueryUid = components['parameters']['QueryUID'];
export type ParameterLimit = components['parameters']['Limit'];
export type ParameterOffset = components['parameters']['Offset'];
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example healthy */
                        status?: string;
                    };
                };
            };
            /** @description Service is unhealthy */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Password change required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordChangeRequiredError"];
                };
            };
            429: components["responses"]["AuthRateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout successful */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user and session info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePasswordPreLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreLoginPasswordChangeRequest"];
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Weak password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        error: "weak_password";
                        message: string;
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["AuthRateLimited"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        users?: components["schemas"]["User"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UID */
                uid: components["parameters"]["UserUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UID */
                uid: components["parameters"]["UserUID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description User updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UID */
                uid: components["parameters"]["UserUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description User UID */
                uid: components["parameters"]["UserUID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Weak password */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        error: "weak_password";
                        message: string;
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Cannot change another user's password (non-admin) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["AuthRateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    listDatabases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of databases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        databases?: (components["schemas"]["Database"] | components["schemas"]["DatabaseLimited"])[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDatabaseRequest"];
            };
        };
        responses: {
            /** @description Database created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Database"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Database UID */
                uid: components["parameters"]["DatabaseUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Database"] | components["schemas"]["DatabaseLimited"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    updateDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Database UID */
                uid: components["parameters"]["DatabaseUID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDatabaseRequest"];
            };
        };
        responses: {
            /** @description Database updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteDatabase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Database UID */
                uid: components["parameters"]["DatabaseUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    listGrants: {
        parameters: {
            query?: {
                /** @description Filter by user UID */
                user_id?: string;
                /** @description Filter by database UID */
                database_id?: string;
                /** @description Only return active (non-revoked, within time window) grants */
                active_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of grants */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        grants?: components["schemas"]["AccessGrant"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createGrant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGrantRequest"];
            };
        };
        responses: {
            /** @description Grant created successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessGrant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getGrant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Grant UID */
                uid: components["parameters"]["GrantUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grant details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessGrant"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    revokeGrant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Grant UID */
                uid: components["parameters"]["GrantUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grant revoked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    listAPIKeys: {
        parameters: {
            query?: {
                /** @description Filter by user UID (admin only) */
                user_id?: string;
                /** @description Include revoked and expired keys */
                include_all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of API keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys?: components["schemas"]["APIKey"][];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    createAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAPIKeyRequest"];
            };
        };
        responses: {
            /** @description API key created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAPIKeyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKey"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    revokeAPIKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key revoked successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    listConnections: {
        parameters: {
            query?: {
                /** @description Filter by user UID */
                user_id?: string;
                /** @description Filter by database UID */
                database_id?: string;
                /** @description Maximum number of results to return */
                limit?: components["parameters"]["Limit"];
                /** @description Number of results to skip for pagination */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of connections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        connections?: components["schemas"]["Connection"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    listQueries: {
        parameters: {
            query?: {
                /** @description Filter by connection UID */
                connection_id?: string;
                /** @description Filter by user UID */
                user_id?: string;
                /** @description Filter by database UID */
                database_id?: string;
                /** @description Filter by start time (RFC3339 format) */
                start_time?: string;
                /** @description Filter by end time (RFC3339 format) */
                end_time?: string;
                /** @description Maximum number of results to return */
                limit?: components["parameters"]["Limit"];
                /** @description Number of results to skip for pagination */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of queries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        queries?: components["schemas"]["Query"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
    getQuery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Query UID */
                uid: components["parameters"]["QueryUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Query details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Query"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    getQueryRows: {
        parameters: {
            query?: {
                /** @description Pagination cursor from previous response */
                cursor?: string;
                /** @description Maximum number of rows to return */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Query UID */
                uid: components["parameters"]["QueryUID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Query rows retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QueryRowsResponse"];
                };
            };
            /** @description Invalid cursor or limit */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimited"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                /** @description Filter by event type (e.g., user.created, grant.revoked) */
                event_type?: string;
                /** @description Filter by user UID (the user being acted upon) */
                user_id?: string;
                /** @description Filter by performer UID (the user performing the action) */
                performed_by?: string;
                /** @description Filter by start time (RFC3339 format) */
                start_time?: string;
                /** @description Filter by end time (RFC3339 format) */
                end_time?: string;
                /** @description Maximum number of results to return */
                limit?: components["parameters"]["Limit"];
                /** @description Number of results to skip for pagination */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        audit_events?: components["schemas"]["AuditEvent"][];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
            500: components["responses"]["InternalError"];
        };
    };
}
