package mysql

import (
	"crypto/rsa"
	"errors"
	"testing"

	"github.com/fclairamb/dbbat/internal/config"
)

func TestLoadTLSAndRSA_Disabled(t *testing.T) {
	t.Parallel()

	tlsConf, key, err := loadTLSAndRSA(config.MySQLConfig{
		TLS: config.TLSConfig{Disable: true},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if tlsConf != nil {
		t.Error("expected nil tls.Config when disabled")
	}

	if key != nil {
		t.Error("expected nil RSA key when disabled")
	}
}

func TestLoadTLSAndRSA_AutoGenerated(t *testing.T) {
	t.Parallel()

	tlsConf, key, err := loadTLSAndRSA(config.MySQLConfig{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if tlsConf == nil {
		t.Fatal("expected non-nil tls.Config")
	}

	if len(tlsConf.Certificates) != 1 {
		t.Fatalf("expected 1 certificate, got %d", len(tlsConf.Certificates))
	}

	if key == nil {
		t.Fatal("expected RSA key to be generated alongside cert")
	}

	if _, ok := tlsConf.Certificates[0].PrivateKey.(*rsa.PrivateKey); !ok {
		t.Error("certificate private key should be *rsa.PrivateKey")
	}
}

func TestLoadTLSAndRSA_PartialPathsRejected(t *testing.T) {
	t.Parallel()

	cases := []config.TLSConfig{
		{CertFile: "cert.pem"},
		{KeyFile: "key.pem"},
	}

	for _, tc := range cases {
		_, _, err := loadTLSAndRSA(config.MySQLConfig{TLS: tc})
		if !errors.Is(err, ErrTLSConfigInvalid) {
			t.Errorf("expected ErrTLSConfigInvalid for %+v, got %v", tc, err)
		}
	}
}

func TestXorWithSalt_Reversible(t *testing.T) {
	t.Parallel()

	// XOR is its own inverse: applying twice with same salt yields the original.
	salt := []byte("abcdefghij1234567890")
	password := []byte("hunter2!")

	encrypted := xorWithSalt(password, salt)
	decrypted := xorWithSalt(encrypted, salt)

	if string(decrypted) != string(password) {
		t.Errorf("xor not reversible: got %q, want %q", decrypted, password)
	}
}

func TestXorWithSalt_EmptySalt(t *testing.T) {
	t.Parallel()

	in := []byte("data")
	out := xorWithSalt(in, nil)

	if string(out) != string(in) {
		t.Errorf("expected passthrough on empty salt, got %q", out)
	}
}

func TestTrimTrailingNUL(t *testing.T) {
	t.Parallel()

	cases := map[string]string{
		"hunter2":       "hunter2",
		"hunter2\x00":   "hunter2",
		"\x00":          "",
		"":              "",
		"a\x00\x00\x00": "a",
	}

	for in, want := range cases {
		if got := trimTrailingNUL(in); got != want {
			t.Errorf("trimTrailingNUL(%q) = %q, want %q", in, got, want)
		}
	}
}
