/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUserGroupsIndexRouteImport } from './routes/_authenticated/user-groups/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers/index'
import { Route as AuthenticatedQueriesIndexRouteImport } from './routes/_authenticated/queries/index'
import { Route as AuthenticatedGrantsIndexRouteImport } from './routes/_authenticated/grants/index'
import { Route as AuthenticatedGrantRequestsIndexRouteImport } from './routes/_authenticated/grant-requests/index'
import { Route as AuthenticatedGrantDefinitionsIndexRouteImport } from './routes/_authenticated/grant-definitions/index'
import { Route as AuthenticatedDatabasesIndexRouteImport } from './routes/_authenticated/databases/index'
import { Route as AuthenticatedConnectionsIndexRouteImport } from './routes/_authenticated/connections/index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedApiKeysIndexRouteImport } from './routes/_authenticated/api-keys/index'
import { Route as AuthenticatedQueriesUidRouteImport } from './routes/_authenticated/queries/$uid'
import { Route as AuthenticatedConnectionsUidRouteImport } from './routes/_authenticated/connections/$uid'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserGroupsIndexRoute =
  AuthenticatedUserGroupsIndexRouteImport.update({
    id: '/user-groups/',
    path: '/user-groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQueriesIndexRoute =
  AuthenticatedQueriesIndexRouteImport.update({
    id: '/queries/',
    path: '/queries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrantsIndexRoute =
  AuthenticatedGrantsIndexRouteImport.update({
    id: '/grants/',
    path: '/grants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrantRequestsIndexRoute =
  AuthenticatedGrantRequestsIndexRouteImport.update({
    id: '/grant-requests/',
    path: '/grant-requests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrantDefinitionsIndexRoute =
  AuthenticatedGrantDefinitionsIndexRouteImport.update({
    id: '/grant-definitions/',
    path: '/grant-definitions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDatabasesIndexRoute =
  AuthenticatedDatabasesIndexRouteImport.update({
    id: '/databases/',
    path: '/databases/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConnectionsIndexRoute =
  AuthenticatedConnectionsIndexRouteImport.update({
    id: '/connections/',
    path: '/connections/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiKeysIndexRoute =
  AuthenticatedApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQueriesUidRoute = AuthenticatedQueriesUidRouteImport.update({
  id: '/queries/$uid',
  path: '/queries/$uid',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConnectionsUidRoute =
  AuthenticatedConnectionsUidRouteImport.update({
    id: '/connections/$uid',
    path: '/connections/$uid',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/connections/$uid': typeof AuthenticatedConnectionsUidRoute
  '/queries/$uid': typeof AuthenticatedQueriesUidRoute
  '/api-keys/': typeof AuthenticatedApiKeysIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/databases/': typeof AuthenticatedDatabasesIndexRoute
  '/grant-definitions/': typeof AuthenticatedGrantDefinitionsIndexRoute
  '/grant-requests/': typeof AuthenticatedGrantRequestsIndexRoute
  '/grants/': typeof AuthenticatedGrantsIndexRoute
  '/queries/': typeof AuthenticatedQueriesIndexRoute
  '/servers/': typeof AuthenticatedServersIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/user-groups/': typeof AuthenticatedUserGroupsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/connections/$uid': typeof AuthenticatedConnectionsUidRoute
  '/queries/$uid': typeof AuthenticatedQueriesUidRoute
  '/api-keys': typeof AuthenticatedApiKeysIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/connections': typeof AuthenticatedConnectionsIndexRoute
  '/databases': typeof AuthenticatedDatabasesIndexRoute
  '/grant-definitions': typeof AuthenticatedGrantDefinitionsIndexRoute
  '/grant-requests': typeof AuthenticatedGrantRequestsIndexRoute
  '/grants': typeof AuthenticatedGrantsIndexRoute
  '/queries': typeof AuthenticatedQueriesIndexRoute
  '/servers': typeof AuthenticatedServersIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/user-groups': typeof AuthenticatedUserGroupsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/connections/$uid': typeof AuthenticatedConnectionsUidRoute
  '/_authenticated/queries/$uid': typeof AuthenticatedQueriesUidRoute
  '/_authenticated/api-keys/': typeof AuthenticatedApiKeysIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/connections/': typeof AuthenticatedConnectionsIndexRoute
  '/_authenticated/databases/': typeof AuthenticatedDatabasesIndexRoute
  '/_authenticated/grant-definitions/': typeof AuthenticatedGrantDefinitionsIndexRoute
  '/_authenticated/grant-requests/': typeof AuthenticatedGrantRequestsIndexRoute
  '/_authenticated/grants/': typeof AuthenticatedGrantsIndexRoute
  '/_authenticated/queries/': typeof AuthenticatedQueriesIndexRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/user-groups/': typeof AuthenticatedUserGroupsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/connections/$uid'
    | '/queries/$uid'
    | '/api-keys/'
    | '/audit/'
    | '/connections/'
    | '/databases/'
    | '/grant-definitions/'
    | '/grant-requests/'
    | '/grants/'
    | '/queries/'
    | '/servers/'
    | '/settings/'
    | '/user-groups/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/connections/$uid'
    | '/queries/$uid'
    | '/api-keys'
    | '/audit'
    | '/connections'
    | '/databases'
    | '/grant-definitions'
    | '/grant-requests'
    | '/grants'
    | '/queries'
    | '/servers'
    | '/settings'
    | '/user-groups'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/connections/$uid'
    | '/_authenticated/queries/$uid'
    | '/_authenticated/api-keys/'
    | '/_authenticated/audit/'
    | '/_authenticated/connections/'
    | '/_authenticated/databases/'
    | '/_authenticated/grant-definitions/'
    | '/_authenticated/grant-requests/'
    | '/_authenticated/grants/'
    | '/_authenticated/queries/'
    | '/_authenticated/servers/'
    | '/_authenticated/settings/'
    | '/_authenticated/user-groups/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user-groups/': {
      id: '/_authenticated/user-groups/'
      path: '/user-groups'
      fullPath: '/user-groups/'
      preLoaderRoute: typeof AuthenticatedUserGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queries/': {
      id: '/_authenticated/queries/'
      path: '/queries'
      fullPath: '/queries/'
      preLoaderRoute: typeof AuthenticatedQueriesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grants/': {
      id: '/_authenticated/grants/'
      path: '/grants'
      fullPath: '/grants/'
      preLoaderRoute: typeof AuthenticatedGrantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grant-requests/': {
      id: '/_authenticated/grant-requests/'
      path: '/grant-requests'
      fullPath: '/grant-requests/'
      preLoaderRoute: typeof AuthenticatedGrantRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/grant-definitions/': {
      id: '/_authenticated/grant-definitions/'
      path: '/grant-definitions'
      fullPath: '/grant-definitions/'
      preLoaderRoute: typeof AuthenticatedGrantDefinitionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/databases/': {
      id: '/_authenticated/databases/'
      path: '/databases'
      fullPath: '/databases/'
      preLoaderRoute: typeof AuthenticatedDatabasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections/': {
      id: '/_authenticated/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof AuthenticatedConnectionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys/': {
      id: '/_authenticated/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof AuthenticatedApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queries/$uid': {
      id: '/_authenticated/queries/$uid'
      path: '/queries/$uid'
      fullPath: '/queries/$uid'
      preLoaderRoute: typeof AuthenticatedQueriesUidRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/connections/$uid': {
      id: '/_authenticated/connections/$uid'
      path: '/connections/$uid'
      fullPath: '/connections/$uid'
      preLoaderRoute: typeof AuthenticatedConnectionsUidRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedConnectionsUidRoute: typeof AuthenticatedConnectionsUidRoute
  AuthenticatedQueriesUidRoute: typeof AuthenticatedQueriesUidRoute
  AuthenticatedApiKeysIndexRoute: typeof AuthenticatedApiKeysIndexRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedConnectionsIndexRoute: typeof AuthenticatedConnectionsIndexRoute
  AuthenticatedDatabasesIndexRoute: typeof AuthenticatedDatabasesIndexRoute
  AuthenticatedGrantDefinitionsIndexRoute: typeof AuthenticatedGrantDefinitionsIndexRoute
  AuthenticatedGrantRequestsIndexRoute: typeof AuthenticatedGrantRequestsIndexRoute
  AuthenticatedGrantsIndexRoute: typeof AuthenticatedGrantsIndexRoute
  AuthenticatedQueriesIndexRoute: typeof AuthenticatedQueriesIndexRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedUserGroupsIndexRoute: typeof AuthenticatedUserGroupsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedConnectionsUidRoute: AuthenticatedConnectionsUidRoute,
  AuthenticatedQueriesUidRoute: AuthenticatedQueriesUidRoute,
  AuthenticatedApiKeysIndexRoute: AuthenticatedApiKeysIndexRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedConnectionsIndexRoute: AuthenticatedConnectionsIndexRoute,
  AuthenticatedDatabasesIndexRoute: AuthenticatedDatabasesIndexRoute,
  AuthenticatedGrantDefinitionsIndexRoute:
    AuthenticatedGrantDefinitionsIndexRoute,
  AuthenticatedGrantRequestsIndexRoute: AuthenticatedGrantRequestsIndexRoute,
  AuthenticatedGrantsIndexRoute: AuthenticatedGrantsIndexRoute,
  AuthenticatedQueriesIndexRoute: AuthenticatedQueriesIndexRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedUserGroupsIndexRoute: AuthenticatedUserGroupsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
