import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The docs sidebar is generated from the file tree, so a new page joins it by
// existing — there is no list to append to here. Ordering and labels come from
// each page's front matter (`sidebar_position`, `sidebar_label`) and from the
// `_category_.json` in each directory. Current top-level order: Introduction
// (1), Installation (2), Configuration (3), Features (4), API Reference (5),
// Compliance (6), then Changelog (100) and the unpositioned pages.
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
